- platform: mqtt
  name: 'TV'
  state_topic: 'smartthings/Tv/switch'
  command_topic: 'smartthings/Tv/switch'
  payload_on: 'on'
  payload_off: 'off'
  retain: true
- platform: mqtt
  name: 'Stereo'
  state_topic: 'smartthings/Stereo/switch'
  command_topic: 'smartthings/Stereo/switch'
  payload_on: 'on'
  payload_off: 'off'
  retain: true
- platform: mqtt
  name: 'Antenna'
  state_topic: 'smartthings/Antenna/switch'
  command_topic: 'smartthings/Antenna/switch'
  payload_on: 'on'
  payload_off: 'off'
  retain: true
- platform: mqtt
  name: 'Chromecast'
  state_topic: 'smartthings/Chromecast/switch'
  command_topic: 'smartthings/Chromecast/switch'
  payload_on: 'on'
  payload_off: 'off'
  retain: true
- platform: mqtt
  name: 'Roku'
  state_topic: 'smartthings/Roku/switch'
  command_topic: 'smartthings/Roku/switch'
  payload_on: 'on'
  payload_off: 'off'
  retain: true
